"use client"

import {
  AlertTriangle,
  ChevronsDown,
  Terminal,
  Hash,
  BookMarked,
  RectangleHorizontal,
  BadgeCheck,
  ChevronRight,
  CalendarDays,
  CreditCard,
  CheckSquare,
  ChevronsUpDown,
  MousePointerClick,
  Inbox,
  Keyboard,
  PanelTop,
  ChevronDown,
  TextCursorInput,
  Tag,
  Layers,
  CircleDot,
  ListFilter,
  SeparatorHorizontal,
  PanelRight,
  LayoutDashboard,
  Square,
  Bell,
  Table2,
  Columns3,
  AlignLeft,
  ToggleLeft,
  MessageSquare,
  Pipette,
  Palette,
  TableProperties,
  FunctionSquare,
  Upload,
  SplitSquareHorizontal,
  TextCursor,
  MousePointer2,
  KeyRound,
  ArrowLeftRight,
  ShieldAlert,
  SquarePen,
  Filter,
  Users,
  Link2,
  LogIn,
  UserPlus,
  Smartphone,
  Mail,
  Lock,
  Shield,
  UserCog,
  Building2,
  Users2,
  ShieldCheck,
  Component,
  type LucideIcon,
} from "lucide-react"

const iconMap: Record<string, LucideIcon> = {
  accordion: ChevronsDown,
  alert: AlertTriangle,
  avatar: CircleDot,
  badge: BadgeCheck,
  breadcrumb: ChevronRight,
  button: RectangleHorizontal,
  calendar: CalendarDays,
  card: CreditCard,
  checkbox: CheckSquare,
  collapsible: ChevronsUpDown,
  command: Terminal,
  "confirm-dialog": ShieldAlert,
  "context-menu": MousePointerClick,
  "color-picker": Pipette,
  "color-swatch": Palette,
  "data-table": TableProperties,
  "empty-state": Inbox,
  "file-upload": Upload,
  "form-section": SquarePen,
  kbd: Keyboard,
  "formula-editor": FunctionSquare,
  "app-switcher": ArrowLeftRight,
  dialog: PanelTop,
  "dropdown-menu": ChevronDown,
  input: TextCursorInput,
  "input-otp": Hash,
  label: Tag,
  "live-caret": TextCursor,
  "live-cursor": MousePointer2,
  pagination: BookMarked,
  popover: Layers,
  "radio-group": CircleDot,
  "search-filter-bar": Filter,
  select: ListFilter,
  separator: SeparatorHorizontal,
  "password-input": KeyRound,
  sheet: PanelRight,
  sidebar: LayoutDashboard,
  skeleton: Square,
  "split-button": SplitSquareHorizontal,
  sonner: Bell,
  table: Table2,
  tabs: Columns3,
  textarea: AlignLeft,
  toggle: ToggleLeft,
  tooltip: MessageSquare,
  "social-links": Link2,
  "user-status": Users,
  "auth-login": LogIn,
  "auth-register": UserPlus,
  "authorized-devices": Smartphone,
  "email-update-form": Mail,
  "password-reset-form": Lock,
  "mfa-form": Shield,
  "profile-form": UserCog,
  "account-deletion-form": AlertTriangle,
  "org-settings-form": Building2,
  "org-roles-form": ShieldCheck,
  "org-members-form": Users2,
}

export function ComponentHeroIcon({ name }: { name: string }) {
  const Icon = iconMap[name] ?? Component

  return (
    <Icon
      className="absolute right-0 top-1/2 -translate-y-1/2 size-28 text-foreground/4 -rotate-12 pointer-events-none"
      strokeWidth={1.5}
    />
  )
}

export function getComponentIcon(name: string): LucideIcon {
  return iconMap[name] ?? Component
}
